### ISSUE TITLE
To-Do!

### ISSUE THREAD

**Issue by williamtdr** [williamtdr/Steadfast#12]
- [x] Sometimes client will crash before reaching 'building terrain' screen and joining the server
- [ ] Players' positions update way less frequently than the used to, causes slower movement
- [x] After switching worlds, the new terrain does not render on the client before a block is broken or apps are switched - client bug, working on a workaround
- [ ] Under some areas of maps with blocks above, lighting is not proper.

**Comment by alejzeis** [comment]
@williamtdr the client crash I believe is a client probelm, not server.

**Comment by tnytown** [comment]
Then we should see it happening consistently on PocketMine-MP 1.4, too. No, it's not client side. We're doing something wrong.

**Comment by tnytown** [comment]
Then we should see it happening consistently on PocketMine-MP 1.4, too. No, it's not client side. We're doing something wrong.

**Comment by alejzeis** [comment]
@KnownUnown it is happening on pocketmine, apparently they fixed it in 0.10.
